/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author lenovo
 */
public class PenampilGambarFullscreen extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarComboboxFullsreen
     */
    public PenampilGambarFullscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPanel = new javax.swing.JPanel();
        btnSolev = new javax.swing.JButton();
        btnOmre = new javax.swing.JButton();
        btnWb = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        imgPanel = new javax.swing.JPanel();
        lbSolev = new javax.swing.JLabel();
        lbOmre = new javax.swing.JLabel();
        lbWb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 700));

        btnPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        btnSolev.setText("Solo Leveling");
        btnSolev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolevActionPerformed(evt);
            }
        });
        btnPanel.add(btnSolev);

        btnOmre.setText("Omni Reader");
        btnOmre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmreActionPerformed(evt);
            }
        });
        btnPanel.add(btnOmre);

        btnWb.setText("Wind Breaker");
        btnWb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWbActionPerformed(evt);
            }
        });
        btnPanel.add(btnWb);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        btnPanel.add(btnKeluar);

        getContentPane().add(btnPanel, java.awt.BorderLayout.NORTH);
        btnPanel.getAccessibleContext().setAccessibleDescription("");

        imgPanel.setLayout(new java.awt.CardLayout());

        lbSolev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSolev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpeg"))); // NOI18N
        imgPanel.add(lbSolev, "0");

        lbOmre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOmre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpeg"))); // NOI18N
        imgPanel.add(lbOmre, "1");

        lbWb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.jpeg"))); // NOI18N
        imgPanel.add(lbWb, "2");

        getContentPane().add(imgPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolevActionPerformed
        CardLayout cl = (CardLayout) (imgPanel.getLayout());
        cl.show(imgPanel, "0");
    }//GEN-LAST:event_btnSolevActionPerformed

    private void btnOmreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmreActionPerformed
        CardLayout cl = (CardLayout) (imgPanel.getLayout());
        cl.show(imgPanel, "1");
    }//GEN-LAST:event_btnOmreActionPerformed

    private void btnWbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWbActionPerformed
        CardLayout cl = (CardLayout) (imgPanel.getLayout());
        cl.show(imgPanel, "2");
    }//GEN-LAST:event_btnWbActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PenampilGambarFullscreen fullFrame = new PenampilGambarFullscreen();
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnOmre;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSolev;
    private javax.swing.JButton btnWb;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel lbOmre;
    private javax.swing.JLabel lbSolev;
    private javax.swing.JLabel lbWb;
    // End of variables declaration//GEN-END:variables
}
